name: Download and Release EPG

on:
  workflow_dispatch:   # запуск вручную
  schedule:
    - cron: "0 3 * * *"   # запуск каждый день в 03:00 UTC

jobs:
  release_epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download epg.xml.gz
        run: |
          curl -L https://epg.online/epg.xml.gz -o epg.xml.gz

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: "EPG Release ${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload epg.xml.gz to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./epg.xml.gz
          asset_name: epg.xml.gz
          asset_content_type: application/gzip
